apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: simeple-mc-deploy-demo
  namespace: examples
spec:
  components:
    - name: nginx-mc-demo
      type: webservice
      properties:
        image: nginx
      traits:
        - type: expose
          properties:
            port: [80]
  policies:
    - name: topology-multi-clusters
      type: topology
      properties:
        clusters: ["cluster2", "oke-sg"]
